services:
  - type: web
    name: agente-personal-telegram
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: GITHUB_TOKEN_1
        sync: false
      - key: GITHUB_TOKEN_2
        sync: false
      - key: GITHUB_TOKEN_3
        sync: false
      - key: GITHUB_TOKEN_4
        sync: false
      - key: GITHUB_TOKEN_5
        sync: false
